# Context
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
env:
  global:
    CC_TEST_REPORTER_ID=6e9f72c700e6fa38deeb5e4287b12f6a6dfcf67ce8638128c9959ad6e873f2a7

# Dependencies
before_install: 
  # Bundler
  - gem install bundler -v 1.16.5
  # Code climate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  bundle install

# Scripts
script:
  rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT